-- Deprecated snapshot file.
-- The canonical schema now lives in:
--   supabase/migrations/20260101000000_initial_schema.sql
--   supabase/migrations/20260102000000_add_vector_index.sql
--
-- Keep this file as a pointer to avoid accidental execution of older,
-- conflicting SQL snippets.
